language: csharp
solution: tactics.sln
sudo: required
services:
- postgresql
- redis-server
install:
- ./TravisScripts/install.sh

script:
- ./TravisScripts/build.sh
- ./TravisScripts/run_tests.sh

after_script:
- cat ./Server/trace.log