language: objective-c
sudo: required
osx_image: xcode61
rvm:
- 2.1.2
services:
- postgresql
- redis-server
install:
- ./TravisScripts/install.sh

script:
- ./TravisScripts/build.sh
- ./TravisScripts/run_tests.sh

after_script:
- cat ./Server/trace.log