language: objective-c
sudo: required

osx_image: xcode8.3.3
rvm:
- 2.1.2

install:
- ./TravisScripts/install.sh

script:
- ./TravisScripts/run_tests.sh
- ./TravisScripts/run_unity_tests.sh

after_script:
- cat ./unity_tests.log
- cat ./EditorTestResults.xml
- cat ./Server/trace.log

notifications:
  slack: dbn16:jT35x7zWh66YQfk4MMFZ0KvD