language: python
sudo: required
services:
- postgresql
- redis-server
install:
- ./TravisScripts/install.sh

before_script:
- python ./Server/manage.py runserver 0.0.0.0:8000 &

script:
- ./TravisScripts/build.sh
- python ./Server/manage.py test