language: objective-c
sudo: required

osx_image: xcode61
rvm:
- 2.1.2

install:
- ./TravisScripts/install.sh

script:
- ./TravisScripts/run_tests.sh
- ./TravisScripts/run_unity_tests.sh

after_script:
- cat ./Server/trace.log

notifications:
  slack: dbn16:jT35x7zWh66YQfk4MMFZ0KvD