language: csharp
solution: tactics.sln
sudo: required
install:
- brew services start postgresql
- brew install redis
- brew services start redis
- ./TravisScripts/install.sh

script:
- ./TravisScripts/build.sh
- ./TravisScripts/run_tests.sh

after_script:
- cat ./Server/trace.log