language: objective-c
sudo: required
osx_image: xcode61
rvm:
- 2.1.2
install:
- export PG_DATA=$(brew --prefix)/var/postgres
- rm -rf $PG_DATA
- initdb $PG_DATA -E utf8
- pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
- createuser -s postgres
- brew update
- brew install redis
- brew services start redis
- redis-server --daemonize yes
- ./TravisScripts/install.sh

script:
- ./TravisScripts/build.sh
- ./TravisScripts/run_tests.sh

after_script:
- cat ./Server/trace.log