language: objective-c
sudo: required
osx_image: xcode61
rvm:
- 2.1.2
install:
- brew services start postgresql
- brew install redis-server
- brew services start redis-server
- ./TravisScripts/install.sh

script:
- ./TravisScripts/build.sh
- ./TravisScripts/run_tests.sh

after_script:
- cat ./Server/trace.log