language: python
sudo: required

services:
- docker

install:
- docker pull akkowal2/tactics-server-tests:latest

script:
- docker run -i -v `pwd`:/Tactics --rm tactics-server-tests

notifications:
  slack: dbn16:jT35x7zWh66YQfk4MMFZ0KvD