language: objective-c
sudo: required
osx_image: xcode61
rvm:
- 2.1.2
install:
- pg_ctl -D /usr/local/var/postgres start
- createuser -s postgres
- brew install redis
- brew services start redis
- ./TravisScripts/install.sh

script:
- ./TravisScripts/build.sh
- ./TravisScripts/run_tests.sh

after_script:
- cat ./Server/trace.log