# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-25 03:21
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pref_grid',
        ),
        migrations.AddField(
            model_name='users',
            name='prefs',
            field=jsonfield.fields.JSONField(default={'Grid Opacity': 100}),
        ),
    ]
