# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-25 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0003_auto_20170313_1314'),
        ('User', '0002_auto_20180225_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice'),
        ),
    ]
