# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asyncmessages',
            old_name='sent',
            new_name='websocket_sent',
        ),
        migrations.AddField(
            model_name='asyncmessages',
            name='device_icon',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='asyncmessages',
            name='device_message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='asyncmessages',
            name='device_sound',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='asyncmessages',
            name='device_title',
            field=models.TextField(default=None, null=True),
        ),
    ]
