# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-02 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncmessages',
            name='device_message',
            field=models.TextField(default='Your troops need you!'),
        ),
        migrations.AddField(
            model_name='asyncmessages',
            name='device_title',
            field=models.TextField(default='Tactics'),
        ),
    ]
