# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Static', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('turn_number', models.IntegerField()),
                ('old_x', models.IntegerField()),
                ('new_x', models.IntegerField()),
                ('old_y', models.IntegerField()),
                ('new_y', models.IntegerField()),
                ('old_hp', models.IntegerField()),
                ('new_hp', models.IntegerField(default=-1)),
                ('unit_missed', models.BooleanField(default=False)),
                ('unit_crit', models.BooleanField(default=False)),
                ('tgt_old_hp', models.IntegerField(default=-1)),
                ('tgt_new_hp', models.IntegerField(default=-1)),
                ('tgt_counter', models.BooleanField(default=False)),
                ('tgt_missed', models.BooleanField(default=False)),
                ('tgt_crit', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_move', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('map_path', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Map')),
                ('user_turn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Game_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25, null=True)),
                ('team', models.IntegerField(default=0)),
                ('victorious', models.BooleanField(default=False)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Game')),
                ('leader_abil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Leader_Ability')),
                ('perk_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='perk_1', to='Static.Perk')),
                ('perk_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='perk_2', to='Static.Perk')),
                ('perk_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='perk_3', to='Static.Perk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acted', models.BooleanField(default=False)),
                ('hp', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=-1)),
                ('y', models.IntegerField(default=-1)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users')),
                ('target', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Unit')),
                ('unit_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Class')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version')),
            ],
        ),
        migrations.AddField(
            model_name='action_history',
            name='acting_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acting_unit', to='Game.Unit'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='acting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Action'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Game'),
        ),
        migrations.AddField(
            model_name='action_history',
            name='target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_target', to='Game.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='game_user',
            unique_together=set([('name', 'user')]),
        ),
    ]
