# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hero_Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Hero_Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('file_path', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
                ('tier', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('value', models.FloatField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('move', models.FloatField(default=1.0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='terrain',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='stat',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='perk',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='map',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='leader',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='hero_ability',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='class',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AddField(
            model_name='action',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Static.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='terrain',
            unique_together=set([('name', 'unit', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('name', 'unit', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='perk',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=set([('file_path', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='leader',
            unique_together=set([('name', 'ability', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='hero_ability',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('name', 'version')]),
        ),
    ]
