# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_users_device'),
        ('Static', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users'),
        ),
    ]
