// This class is used to show information on the UI
// Values determining actions are generated by the server
public class Stat {

	private string _name;			// The name of the stat
    private int _baseValue;       	// The base value of the stat
    private int _buffValue;       	// The amount of the buff to the stat


#region Setters and Getters
    // Returns _basevalue
    public int BaseValue {
        get {return _baseValue;}
        set {_baseValue = value;}
    }
    // Returns _buffValue
    public int BuffValue {
        get {return _buffValue;}
        set {_buffValue = value;}
    }
    // Return calculated total value of stat
    public int Value {
        get {return _baseValue + _buffValue;}
    }
    // Returns _name
	public string Name {
		get{return _name;}
		set{_name = value;}
	}
#endregion


// Runs when a stat is instantiated
    public Stat(string nam) {
    	// Set name and initialize stat values to 0
    	Name = nam;
        _baseValue = 0;
        _buffValue = 0;
    }

}